//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class q_cevap
    {
        public int cevapId { get; set; }
        public Nullable<int> soruId { get; set; }
        public string cevap { get; set; }
        public Nullable<bool> dogruCvp { get; set; }
    
        public virtual q_soru q_soru { get; set; }
    }
}
