//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class q_genelSonuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public q_genelSonuc()
        {
            this.q_sinavSonuc = new HashSet<q_sinavSonuc>();
        }
    
        public int sinavUniq { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> quizCount { get; set; }
    
        public virtual q_kullanici q_kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<q_sinavSonuc> q_sinavSonuc { get; set; }
    }
}
