//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class q_secenek
    {
        public int cevapId { get; set; }
        public string cevap1 { get; set; }
        public string cevap2 { get; set; }
        public string cevap3 { get; set; }
        public string cevap4 { get; set; }
        public string dogruCvp { get; set; }
        public Nullable<System.Guid> soruUniq { get; set; }
    
        public virtual q_soru q_soru { get; set; }
    }
}
