//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class q_sinavSonuc
    {
        public int sinavId { get; set; }
        public Nullable<bool> dogruMu { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public Nullable<int> puan { get; set; }
        public Nullable<System.DateTime> sinavTarih { get; set; }
        public Nullable<System.Guid> soruUniq { get; set; }
        public Nullable<int> sinavUniq { get; set; }
        public Nullable<int> sinavNo { get; set; }
    
        public virtual q_genelSonuc q_genelSonuc { get; set; }
    }
}
