//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class q_soru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public q_soru()
        {
            this.q_secenek = new HashSet<q_secenek>();
        }
    
        public System.Guid soruUniq { get; set; }
        public string soru { get; set; }
        public Nullable<int> derece { get; set; }
        public Nullable<int> kategoriId { get; set; }
    
        public virtual q_kategori q_kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<q_secenek> q_secenek { get; set; }
    }
}
